-- AlterTable
ALTER TABLE "Metrics" ALTER COLUMN "date" DROP DEFAULT,
ALTER COLUMN "latency" DROP NOT NULL,
ALTER COLUMN "packetLoss" DROP NOT NULL,
ALTER COLUMN "ping" DROP NOT NULL,
ALTER COLUMN "traffic" DROP NOT NULL;
